

version: 2.1

orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5

jobs:
  build:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/scan:
          file: "./ForNeova/msk-cluster.tf"
          api-key-variable: f7835a71f131ca0d5b62123895f00a0df40232f7
          prisma-api-url: https://api.prismacloud.io
